services:
  backend:
    build: .
    container_name: api_backend
    ports: 
      - '3000:3000'
    volumes: 
      - .:/app
      - /app/node_modules
    environment:
       DB_HOST: db
       DB_PORT: 5432
       DB_USER: postgres
       DB_PASSWORD: 1234
       DB_NAME: to_do
       REDIS_HOST: redis
       REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: to_do
    ports:
      - "5432:5432"
    
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"